### PR TITLE
Update FirebaseImpl.java

### PR DESCRIPTION
**Pull request by devoncarew**
Change the adb tag that we log to (https://github.com/flutter/flutter/issues/4061); @collinjackson.

### CODE REVIEW

**Comment by devoncarew** [comment]
@collinjackson

**Comment by collinjackson** [comment]
lgtm

**Comment by devoncarew** [comment]
@collinjackson, can you merge this? Thanks!

**Comment by collinjackson** [comment]
Done. Next time I regenerate files, this will be updated.

**Pull request merged**
